### ISSUE TITLE
BUG: transpose-words

### ISSUE THREAD

**Issue by gdmcbain** [aymen3009/vscode-emacs-transpose#1]
If I place the cursor either side of the comma in 

```julia
		mass = Mass(; m, v)
```

and issue `Alt+t` or `F1` _Transpose Words_, I get

```julia
		vass = Mass(; m, m)
```

whereas I was hoping for

```julia
		mass = Mass(; v, m)
```

**Comment by aymen3009** [comment]
@gdmcbain  Thanks for the report. I was able to reproduce the issue and I just pushed a fix for it. It should be working after you update the extension. Thanks again for the report.

**Comment by gdmcbain** [comment]
My goodness that was quick!  Thank you. :)

I confirm that it works now.

I did accidentally notice something else though.  I won't open a new issue just yet as I don't have GNU Emacs to hand to test against and don't know the desired behaviour, but if I place the cursor within a word but not right in the middle, I get a curious sequence of transformations rather than the involution that I expected.

Put the cursor three letters into to "involution". as in "inv|olution" and repeatedly issue _Transpose Words_:

- involution
- olutioninv
- tioninvolu
- ninvolutio
- volutionin
- utioninvol
- oninvoluti
- nvolutioni
- lutioninvo
- ioninvolut
- involution
 
It moves the three letters to the left of the cursor to the end of the word but leaves the cursor three letters into the new word.  Should the cursor jump to the joining point?  As in "olution|inv", so that another `Alt+t` would undo the first.

**Comment by aymen3009** [comment]
Yeah, moving the cursor to the joining point makes more sense... I will fix this now thanks again :smile:

**Comment by aymen3009** [comment]
@gdmcbain it should be working correctly now

**Comment by gdmcbain** [comment]
Good morning!  Perfect!  I didn't get a chance to check out how Emacs does it, but I'm pretty sure it'd have to be like this.  

- involution
- olutioninv
- involution

Thanks very much!
