### ISSUE TITLE
Transposing words separated by newline

### ISSUE THREAD

**Issue by rbolsius** [aymen3009/vscode-emacs-transpose#3]
It would be nice if the **Transpose Words** command would transpose words around the cursor even if the words are separated by a newline.

For example,

If the cursor position is represented by `|` in the sample text below:

```
one
|two
```

Then after running the **Transpose Words** command, I would expect the following result:

```
two
|one
```

**Comment by aymen3009** [comment]
that's actually a good idea but let me check the emacs behavior first .. for your example transpose line will do the job

**Comment by rbolsius** [comment]
Strangely the **Transpose Line** command doesn't have any effect when I run it.

Also, the example I gave is a bit simplistic. More generally I would expect it to transpose the words on either side of the cursor across newline boundaries even when there are multiple words on a line.

Maybe the following is a better example:

```
one two
|three four
```

After running the Transpose Words command, I would expect the following result:

```
one three
|two four
```

As an aside, the behavior of the Emacs transpose commands differs slightly from this extension in that the cursor in Emacs is positioned after both of the transposed words. I can see the merits of both cursor placements. Emacs makes it easier to repeat the `transpose-words` command to slide a word several places forward within a sentence, while keeping the cursor in the middle of the transposed words makes it easier to swap the words back to the original positions by repeating the command. FWIW, the built-in VS Code command **Transpose Letters** follows the Emacs behavior of placing the cursor after both of the transposed letters.

**Comment by aymen3009** [comment]
@rbolsius I have added the behavior you describe in the latest version please check it out and report any issues you may find. Thanks for pointing this out 😄

**Comment by rbolsius** [comment]
Wow! That was a super fast turn around! The only issue I found with the new update is that if the cursor starts at the beginning of the second line, then after the words are transposed, the cursor is moved to the end of the second line. It would make more sense for the cursor to remain at the beginning of the line in that case.

With the 0.0.4 update this is what I'm seeing.

## Case 1: Cursor is positioned at the beginning of the second line

```
one two
|three four
```

After transposing the words, the cursor jumps to the end of the line.

```
one three
two four|
```

On the other hand if the cursor is at the end of the first line, then it works as expected.

## Case 2: Cursor is positioned at the end of the first line

```
one two|
three four
```

```
one three|
two four
```

**Comment by aymen3009** [comment]
i just pushed a version please wait for it to be published and check it out
